ruby '2.5.1'

source 'https://rubygems.org'

gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'dm-aggregates'
gem 'haml', '~> 5.0', '>= 5.0.4'
gem 'pg'
gem 'puma', '~> 3.11.2'
gem 'rake'
gem 'roo', '~> 2.8.0'
gem 'roo-xls'
gem 'sinatra', '~> 2.0'
gem 'shotgun'
